apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: qat-apply-cr
  namespace: {{ .Values.job.namespace }}
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.job.image }}
          command:
            - /bin/bash
            - -c
            - |
              oc apply -f https://raw.githubusercontent.com/intel/intel-technology-enabling-for-openshift/v1.2.0/device_plugins/qat_device_plugin.yaml
          imagePullPolicy: IfNotPresent
          name: qat-apply-cr
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}